### ISSUE TITLE
Possible issue with the test runner

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/nim-test-runner#162]
My solution runs locally but fails online with:

```
tcc: error: libtcc1.a not found
Error: execution of an external program failed: 'tcc -o test_acronym  -lm -lm -lrt   -ldl    /root/.cache/nim/test_acronym_d/@m..@s..@snim@slib@ssystem@sexceptions.nim.c.o /root/.cache/nim/test_acronym_d/@m..@s..@snim@slib@sstd@ssysatomics.nim.c.o /root/.cache/nim/test_acronym_d/
...
```

My solution is:

```nim
import std/re
import std/strutils

proc abbreviate*(s: string): string =
  var letters: seq[char] = @[]

  for match in re.findAll(s, re"[A-Za-z']+"):
    letters.add(strutils.toUpperAscii(match[0]))

  result = letters.join
```

Is this an issue with the test runner? From the error it looks like an issue with the C compiler, but maybe there's a subtle issue with my code. Perhaps I am not supposed to use these standard libraries?

**Comment by ynfle** [comment]
Hi Ryan, the issue isn't with your code; the problematic code has been reverted. See https://forum.exercism.org/t/nim-test-runner-bug-after-exercism-submit/10088/4.

**Comment by ryanplusplus** [comment]
Thanks!
