### ISSUE TITLE
Dockerfile: `ENTRYPOINT` should be updated

### ISSUE THREAD

**Issue by ee7** [exercism/nim-test-runner#62]
From @ErikSchierboom on Slack

> There is an error for the Nim test runner:

```
exceptioned

STDOUT:
------


STDERR:
------
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
oserr.nim(94)            raiseOSError
Error: unhandled exception: No such file or directory
Additional info: "tests" [OSError]
```

I guess the issue is here:
https://github.com/exercism/nim-test-runner/blob/8c999495bb366f65d058d9cc445385795f3cab85/Dockerfile#L17-L18

If I recall correctly, the spec previously stated that the `ENTRYPOINT` here was overriden in the production environment. But I guess it isn't anymore?

**Comment by ErikSchierboom** [comment]
> If I recall correctly, the spec previously stated that the ENTRYPOINT here was overriden in the production environment. But I guess it isn't anymore?

Nope. We just run it as a regular Docker container without overriding the ENTRYPOINT. See https://github.com/exercism/prolog-test-runner/blob/main/Dockerfile for an up-to-date example.
